//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8806
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.diebold.com/agilis/activities/GetCustomerInput/1.0.0.0/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.diebold.com/agilis/activities/GetCustomerInput/1.0.0.0/", IsNullable=false)]
public partial class Properties {
    
    private string screenNameField;
    
    private int timeOutField;
    
    private string timeOutStateScreenNameField;
    
    private int maxTimeOutRetriesField;
    
    private int timeOutToTimeOutStateField;
    
    private bool timeOutScreenBeepEnabledField;
    
    private bool useEightFDKsField;
    
    private string enableFDKAField;
    
    private string enableFDKBField;
    
    private string enableFDKCField;
    
    private string enableFDKDField;
    
    private string enableFDKFField;
    
    private string enableFDKGField;
    
    private string enableFDKHField;
    
    private string enableFDKIField;
    
    private PropertiesJournal journalField;
    
    public Properties() {
        this.timeOutField = 45;
        this.maxTimeOutRetriesField = 1;
        this.timeOutToTimeOutStateField = 10;
        this.timeOutScreenBeepEnabledField = false;
        this.useEightFDKsField = false;
    }
    
    /// <comentarios/>
    public string ScreenName {
        get {
            return this.screenNameField;
        }
        set {
            this.screenNameField = value;
        }
    }
    
    /// <comentarios/>
    public int TimeOut {
        get {
            return this.timeOutField;
        }
        set {
            this.timeOutField = value;
        }
    }
    
    /// <comentarios/>
    public string TimeOutStateScreenName {
        get {
            return this.timeOutStateScreenNameField;
        }
        set {
            this.timeOutStateScreenNameField = value;
        }
    }
    
    /// <comentarios/>
    public int MaxTimeOutRetries {
        get {
            return this.maxTimeOutRetriesField;
        }
        set {
            this.maxTimeOutRetriesField = value;
        }
    }
    
    /// <comentarios/>
    public int TimeOutToTimeOutState {
        get {
            return this.timeOutToTimeOutStateField;
        }
        set {
            this.timeOutToTimeOutStateField = value;
        }
    }
    
    /// <comentarios/>
    public bool TimeOutScreenBeepEnabled {
        get {
            return this.timeOutScreenBeepEnabledField;
        }
        set {
            this.timeOutScreenBeepEnabledField = value;
        }
    }
    
    /// <comentarios/>
    public bool UseEightFDKs {
        get {
            return this.useEightFDKsField;
        }
        set {
            this.useEightFDKsField = value;
        }
    }
    
    /// <comentarios/>
    public string EnableFDKA {
        get {
            return this.enableFDKAField;
        }
        set {
            this.enableFDKAField = value;
        }
    }
    
    /// <comentarios/>
    public string EnableFDKB {
        get {
            return this.enableFDKBField;
        }
        set {
            this.enableFDKBField = value;
        }
    }
    
    /// <comentarios/>
    public string EnableFDKC {
        get {
            return this.enableFDKCField;
        }
        set {
            this.enableFDKCField = value;
        }
    }
    
    /// <comentarios/>
    public string EnableFDKD {
        get {
            return this.enableFDKDField;
        }
        set {
            this.enableFDKDField = value;
        }
    }
    
    /// <comentarios/>
    public string EnableFDKF {
        get {
            return this.enableFDKFField;
        }
        set {
            this.enableFDKFField = value;
        }
    }
    
    /// <comentarios/>
    public string EnableFDKG {
        get {
            return this.enableFDKGField;
        }
        set {
            this.enableFDKGField = value;
        }
    }
    
    /// <comentarios/>
    public string EnableFDKH {
        get {
            return this.enableFDKHField;
        }
        set {
            this.enableFDKHField = value;
        }
    }
    
    /// <comentarios/>
    public string EnableFDKI {
        get {
            return this.enableFDKIField;
        }
        set {
            this.enableFDKIField = value;
        }
    }
    
    /// <comentarios/>
    public PropertiesJournal Journal {
        get {
            return this.journalField;
        }
        set {
            this.journalField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.diebold.com/agilis/activities/GetCustomerInput/1.0.0.0/")]
public partial class PropertiesJournal {
    
    private bool enableJournalField;
    
    private string inputCancelFileNameField;
    
    private string inputTimeoutFileNameField;
    
    public PropertiesJournal() {
        this.enableJournalField = false;
        this.inputCancelFileNameField = "InputCancel.txt";
        this.inputTimeoutFileNameField = "InputTimeout.txt";
    }
    
    /// <comentarios/>
    public bool EnableJournal {
        get {
            return this.enableJournalField;
        }
        set {
            this.enableJournalField = value;
        }
    }
    
    /// <comentarios/>
    public string InputCancelFileName {
        get {
            return this.inputCancelFileNameField;
        }
        set {
            this.inputCancelFileNameField = value;
        }
    }
    
    /// <comentarios/>
    public string InputTimeoutFileName {
        get {
            return this.inputTimeoutFileNameField;
        }
        set {
            this.inputTimeoutFileNameField = value;
        }
    }
}
